export const SESSION = {
  THEME_MODE: "THEME_MODE",
  TOKEN: "TOKEN",
  MODULES:"MODULES",
  PROFILE_IMG:"PROFILE_IMG",
  SUBMITTER_DATA:"SUBMITTER_DATA",
  FILE_PARTS:"FILE_PARTS",
  SESSION_ID:"SESSION_ID",
};
