export const statesOptions = [
  { name: "Andhra Pradesh", country: "India" },
  { name: "Arunachal Pradesh", country: "India" },
  { name: "Assam", country: "India" },
  { name: "Bihar", country: "India" },
  { name: "Chhattisgarh", country: "India" },
  { name: "Goa", country: "India" },
  { name: "Gujarat", country: "India" },
  { name: "Haryana", country: "India" },
  { name: "Himachal Pradesh", country: "India" },
  { name: "Jharkhand", country: "India" },
  { name: "Karnataka", country: "India" },
  { name: "Kerala", country: "India" },
  { name: "Madhya Pradesh", country: "India" },
  { name: "Maharashtra", country: "India" },
  { name: "Manipur", country: "India" },
  { name: "Meghalaya", country: "India" },
  { name: "Mizoram", country: "India" },
  { name: "Nagaland", country: "India" },
  { name: "Odisha", country: "India" },
  { name: "Punjab", country: "India" },
  { name: "Rajasthan", country: "India" },
  { name: "Sikkim", country: "India" },
  { name: "Tamil Nadu", country: "India" },
  { name: "Telangana", country: "India" },
  { name: "Tripura", country: "India" },
  { name: "Uttar Pradesh", country: "India" },
  { name: "Uttarakhand", country: "India" },
  { name: "West Bengal", country: "India" },
  { name: "Andaman and Nicobar Islands", country: "India" },
  { name: "Chandigarh", country: "India" },
  { name: "Dadra and Nagar Haveli and Daman and Diu", country: "India" },
  { name: "Delhi", country: "India" },
  { name: "Lakshadweep", country: "India" },
  { name: "Puducherry", country: "India" },
  { name: "Alabama", country: "United States" },
  { name: "Alaska", country: "United States" },
  { name: "Arizona", country: "United States" },
  { name: "Arkansas", country: "United States" },
  { name: "California", country: "United States" },
  { name: "Colorado", country: "United States" },
  { name: "Connecticut", country: "United States" },
  { name: "Delaware", country: "United States" },
  { name: "Florida", country: "United States" },
  { name: "Georgia", country: "United States" },
  { name: "Hawaii", country: "United States" },
  { name: "Idaho", country: "United States" },
  { name: "Illinois", country: "United States" },
  { name: "Indiana", country: "United States" },
  { name: "Iowa", country: "United States" },
  { name: "Kansas", country: "United States" },
  { name: "Kentucky", country: "United States" },
  { name: "Louisiana", country: "United States" },
  { name: "Maine", country: "United States" },
  { name: "Maryland", country: "United States" },
  { name: "Massachusetts", country: "United States" },
  { name: "Michigan", country: "United States" },
  { name: "Minnesota", country: "United States" },
  { name: "Mississippi", country: "United States" },
  { name: "Missouri", country: "United States" },
  { name: "Montana", country: "United States" },
  { name: "Nebraska", country: "United States" },
  { name: "Nevada", country: "United States" },
  { name: "New Hampshire", country: "United States" },
  { name: "New Jersey", country: "United States" },
  { name: "New Mexico", country: "United States" },
  { name: "New York", country: "United States" },
  { name: "North Carolina", country: "United States" },
  { name: "North Dakota", country: "United States" },
  { name: "Ohio", country: "United States" },
  { name: "Oklahoma", country: "United States" },
  { name: "Oregon", country: "United States" },
  { name: "Pennsylvania", country: "United States" },
  { name: "Rhode Island", country: "United States" },
  { name: "South Carolina", country: "United States" },
  { name: "South Dakota", country: "United States" },
  { name: "Tennessee", country: "United States" },
  { name: "Texas", country: "United States" },
  { name: "Utah", country: "United States" },
  { name: "Vermont", country: "United States" },
  { name: "Virginia", country: "United States" },
  { name: "Washington", country: "United States" },
  { name: "West Virginia", country: "United States" },
  { name: "Wisconsin", country: "United States" },
  { name: "Wyoming", country: "United States" },
  { name: "District of Columbia", country: "United States" },
  { name: "Alberta", country: "Canada" },
  { name: "British Columbia", country: "Canada" },
  { name: "Manitoba", country: "Canada" },
  { name: "New Brunswick", country: "Canada" },
  { name: "Newfoundland and Labrador", country: "Canada" },
  { name: "Nova Scotia", country: "Canada" },
  { name: "Ontario", country: "Canada" },
  { name: "Prince Edward Island", country: "Canada" },
  { name: "Quebec", country: "Canada" },
  { name: "Saskatchewan", country: "Canada" },
  { name: "Northwest Territories", country: "Canada" },
  { name: "Nunavut", country: "Canada" },
];
