import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import GlobalContextProvider from "@/layout/GlobalContextProvider";
import StoreProvider from "@/store/StoreProvider";
import { cookies } from "next/headers";
import { CustomProvider } from "rsuite";
import { redirect } from "next/navigation";
import { MYACCOUNT_LOGIN_URL } from "@/helpers/envis";
const inter = Montserrat({
  subsets: ["latin"],
  style: "normal",
  weight: "600",
  display: "swap",
  adjustFontFallback: true,
  preload: true,
});

export const metadata = {
  title: "Drive",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const tM = cookies().get("theme")?.value;
  const token = cookies().get("fingerPrint")?.value;
  if (!token) {
    // return redirect(`${MYACCOUNT_LOGIN_URL}`);
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <StoreProvider>
            <GlobalContextProvider tM={tM}>
              <CustomProvider theme={tM}>
                {/* <UserData token={token} /> */}
                {children}
              </CustomProvider>
            </GlobalContextProvider>
          </StoreProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
